spring.application.name=arena_feed
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/arena_feed
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
admin.username=admin
admin.password=admin
admin.email=admin@gmail.com